### ISSUE TITLE
NYTimes2018 data is missing

### ISSUE THREAD

**Issue by gkiril** [Yang233666/CMVC#1]
Hi,

When I click on the link provided in the README for the NYTimes2018 data, I get the message "You don't have permission to access /~xlinai/ICDE2019_data.html on this server." Could you please update the link?

**Comment by Yang233666** [comment]
Thank you very much for your issue, this is because the original author of ICDE 2019 modified her homepage. 

Please download the NYTimes2018 data set from the webpage of its original author:  https://heathersherry.github.io/ICDE2019_data.html

**Comment by Yang233666** [comment]
The address of the NYTimes2018 was updated. Thus this issue will be closed.
