### ISSUE TITLE
../init_dict/Entity_linking_dict/Whole_Ranked_Merged_Current_dictionary_UTF-8.txt missing

### ISSUE THREAD

**Issue by LIANGKE23** [Yang233666/CMVC#2]
Hi, I cannot find such txt file~?

How can I get it?

**Comment by Yang233666** [comment]
Please download the init_dict folder from this webpage: 
https://drive.google.com/file/d/17xYnisHhpFcYwHgF3-kYquw2ZZqV9-3Y/view?usp=sharing

**Comment by LIANGKE23** [comment]
Thanks for your reply!!
I have another question, how much RAM does this code need?
I find that the code doesn't rely on GPU, more based on CPU. I have the ram 32 GB, but after the third epoch, my computer goes crashes.

**Comment by Yang233666** [comment]
The machine I'm using has 128GB of RAM and I think at least 70GB is required.

**Comment by Yang233666** [comment]
This issue will be closed.
