### ISSUE TITLE
How to read OPIEC59K dataset?

### ISSUE THREAD

**Issue by ERBD** [Yang233666/CMVC#5]
would you please guide me to read the "OPIEC59K" dataset?

**Comment by Yang233666** [comment]
To read it, you have to import the pickle module first. Then you can use pickle.load() function to do that. The primary argument of pickle load function is the file object that you get by opening the file in read-binary (rb) mode. 

For example, you can use the code (line 6) in the CMVC_main_opiec.py as follows:
self.triples_list = pickle.load(open(args.data_path, 'rb'))

**Comment by Yang233666** [comment]
This issue will be closed.
