### ISSUE TITLE
No such file or directory: '../file/OPIEC59k_test/WEB_seed/entity/cluster_list_threshold_0.015_url_max_length_all'

### ISSUE THREAD

**Issue by ERBD** [Yang233666/CMVC#6]
This file is not created automatically. What do you think I should do to solve this? I want to run the model using OPIEC59k dataset.

**Comment by Yang233666** [comment]
You can use this file directly instead of creating it yourself, which is the easiest way. You can also generate it by reading the Appendix C section in the paper.

**Comment by Yang233666** [comment]
this issue will be closed.
