### ISSUE TITLE
UnboundLocalError: local variable 'context_view_label' referenced before assignment

### ISSUE THREAD

**Issue by ERBD** [Yang233666/CMVC#7]
Would you please check the following error in the `embeddings_multi_view.py` file line 433?
` old_label, new_label = context_view_label, self.label`

**Comment by Yang233666** [comment]
Thanks for your question. Actually, that part is trying to get the performance of context view and it is not really important. I have updated it and you can use the new code.

**Comment by Yang233666** [comment]
The code was updated. Thus this issue will be closed.
